# Generated by Django 4.2.3 on 2023-08-05 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mood', models.CharField(choices=[('happy', 'Happy 😃'), ('peaceful', 'Peaceful 😃'), ('sad', 'Sad 😢'), ('mad', 'Mad 😤'), ('anxious', 'Anxious 😰'), ('depressed', 'Depressed 😓'), ('moodless', 'No Mood 😑'), ('angry', 'Angry 😤'), ('excited', 'Excited 😃'), ('silly', 'Silly 😋'), ('curious', 'Curious 🦝'), ('insightful', 'Insightful 🤔')], default='happy', max_length=20, verbose_name='Current Mood:')),
                ('feeling', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, verbose_name='On a scale 1-10 how strong is your mood:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
