# Generated by Django 4.2.3 on 2023-09-01 03:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPages', '0002_usercontent_graditude_alter_usercontent_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontent',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
