# Generated by Django 4.2.3 on 2023-09-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPages', '0003_alter_usercontent_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontent',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
