# Generated by Django 4.2.3 on 2023-10-06 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPages', '0008_alter_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
    ]
